version: '3.8'

services:
  app:
    build: ./
    command: ./internship-avito
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=1234

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5434:5432"