version: '3.8'

services:
  app:
    build: ./
    command: ./wait-for-postgres.sh db ./internship-avito
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=avito

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=avito
      - POSTGRES_USER=avito
      - POSTGRES_DB=avito
    ports:
      - "5433:5432"